/*
 * Copyright 2017 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import UIKit

// ------------------------------------
// Icon drawing
// Code generated by PaintCode
// ------------------------------------

class WMAlertIconStyleKit: NSObject {
    
    // Cache
    struct Cache {
        static var imageOfCheckmark: UIImage?
    }
    
    // Drawing Methods
    class func drawCheckmark() {
        let fillColor = UIColor(red: 0.357, green: 0.780, blue: 0.365, alpha: 1.000)
        let path3491Path = UIBezierPath()
        path3491Path.move(to: CGPoint(x: 28.78, y: 53.97))
        path3491Path.addLine(to: CGPoint(x: 61.03, y: 21.72))
        path3491Path.addLine(to: CGPoint(x: 55.99, y: 16.52))
        path3491Path.addLine(to: CGPoint(x: 28.78, y: 43.73))
        path3491Path.addLine(to: CGPoint(x: 16.01, y: 30.96))
        path3491Path.addLine(to: CGPoint(x: 10.97, y: 36))
        path3491Path.addLine(to: CGPoint(x: 28.78, y: 53.97))
        path3491Path.close()
        path3491Path.move(to: CGPoint(x: 10.64, y: 10.8))
        path3491Path.addCurve(
            to: CGPoint(x: 36, y: 0.22),
            controlPoint1: CGPoint(x: 17.69, y: 3.75),
            controlPoint2: CGPoint(x: 26.15, y: 0.22)
        )
        path3491Path.addCurve(
            to: CGPoint(x: 61.2, y: 10.8),
            controlPoint1: CGPoint(x: 45.85, y: 0.22),
            controlPoint2: CGPoint(x: 54.25, y: 3.75)
        )
        path3491Path.addCurve(
            to: CGPoint(x: 71.78, y: 36),
            controlPoint1: CGPoint(x: 68.25, y: 17.75),
            controlPoint2: CGPoint(x: 71.78, y: 26.15)
        )
        path3491Path.addCurve(
            to: CGPoint(x: 61.2, y: 61.36),
            controlPoint1: CGPoint(x: 71.78, y: 45.85),
            controlPoint2: CGPoint(x: 68.25, y: 54.31)
        )
        path3491Path.addCurve(
            to: CGPoint(x: 36, y: 71.78),
            controlPoint1: CGPoint(x: 54.25, y: 68.31),
            controlPoint2: CGPoint(x: 45.85, y: 71.78)
        )
        path3491Path.addCurve(
            to: CGPoint(x: 10.64, y: 61.36),
            controlPoint1: CGPoint(x: 26.15, y: 71.78),
            controlPoint2: CGPoint(x: 17.69, y: 68.31)
        )
        path3491Path.addCurve(
            to: CGPoint(x: 0.22, y: 36),
            controlPoint1: CGPoint(x: 3.69, y: 54.31),
            controlPoint2: CGPoint(x: 0.22, y: 45.85)
        )
        path3491Path.addCurve(
            to: CGPoint(x: 10.64, y: 10.8),
            controlPoint1: CGPoint(x: 0.22, y: 26.15),
            controlPoint2: CGPoint(x: 3.69, y: 17.75)
        )
        path3491Path.close()
        path3491Path.usesEvenOddFillRule = true
        fillColor.setFill()
        path3491Path.fill()
    }
    
    // Generated Images
    class var imageOfCheckmark: UIImage {
        if Cache.imageOfCheckmark != nil {
            return Cache.imageOfCheckmark!
        }
        UIGraphicsBeginImageContextWithOptions(CGSize(width: 72, height: 72), false, 0)
        WMAlertIconStyleKit.drawCheckmark()
        Cache.imageOfCheckmark = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        return Cache.imageOfCheckmark!
    }
    
}
